### ISSUE TITLE
Allow adding attachments to blog posts

### ISSUE THREAD

**Issue by Bishwin** [hacking-science/hacking-science-website#14]
### What would you like to change?
enable posters to add attachments to their posts. attachments could be items like images, PDF/docs or hyperlinks to online resources/websites,

### How do you think that would improve the project?
Allow linking to post specific information such as resources for that session or to raise attention to a cool website

**Comment by alectronic0** [comment]
Early suggestion would to add a image Field to post object (be it local reference to the application or a http URL)
Forever who takes this on to consider XSS attacks from reference files.
