### ISSUE TITLE
Allow adding embedded media to posts

### ISSUE THREAD

**Issue by Bishwin** [hacking-science/hacking-science-website#15]
### What would you like to change?
Allow adding embedded media to posts
### How do you think that would improve the project?
This will allow posters to submit videos of relevant material or to showcase upcoming events or scientific videos

How would this look on a post, would it be possible to include a thumbnail? would we have to use a web-scrapping tool (Abdul mentioned this) .

**Comment by crabdul** [comment]
I'm assuming this feature has been implemented in #70 

correct me if i'm wrong
