### ISSUE TITLE
Adding a footer to the base html 

### ISSUE THREAD

**Issue by harjeetkalsi** [hacking-science/hacking-science-website#36]
We currently have a nav-bar but no footer,  there should be a footer which fits the current colour and design of the website. On the footer, there should be a contact part which says our email: info@hackingeducation.io  (when we have a facebook/ instagram account, these should also be placed in the footer)

This ticket will involve coming up with a design, it should also be thought where to position the logo. Should the logo be in the footer or the navbar? 

Please include any screenshots/ links to footers for inspiration: 
https://www.ucl.ac.uk/
https://www.nesta.org.uk/

Perhaps a block footer will stand out more for people to know how to contact, rather than the discrete/ not very bold footer that gitHub has

**Comment by crabdul** [comment]
added in #69
