### ISSUE TITLE
Post Summary 

### ISSUE THREAD

**Issue by harjeetkalsi** [hacking-science/hacking-science-website#40]
Currently when posts appear, they show the title, and the first 200 words of the content. 

Instead of presenting the first 200 words of the content, the user could instead write a short summary and it is this short summary that will be presented on post. 

The 'Summary' will therefore be an extra field in the admin portal when creating a post, it will also need to be added to the posts in models.py and assigned a certain length. The field on the admin portal should therefore tell the user how many works/ when they have gone over the character limit (in a similar way you are only allowed a certain number of characters for a twitter post). 

note only the summary is limited by characters, whereas the content is unlimited and is what appears when the post is clicked on. 

(screen shots/ a design document should be created)

**Comment by crabdul** [comment]
added in #70
