### ISSUE TITLE
Restructuring Directory Structure 

### ISSUE THREAD

**Issue by crabdul** [hacking-science/hacking-science-website#47]
### What would you like to change?

Move static files like home, subscribe, about out of the blog app

### How do you think that would improve the project?

Separation of concerns

**Comment by crabdul** [comment]
@harjeetkalsi What do you reckon? I think the blog folder should only contain blog related files.

**Comment by Bishwin** [comment]
Everything related to the blog app should remind in that directory. It's possible to make apps for other sections of the site, similar to `MapToBreathe`.

I don't think it would make sense to move subscribe as it will let users `subscribe` to blog updates?
That leaves `home` but i don't think there is enough content in that section of the website to warrant a separate app.
@MaxAwan thoughts?

**Comment by alectronic0** [comment]
At the moment I see why we separated room to breathe from the current app

**Comment by alectronic0** [comment]
At the moment we are just build a website which contains blogs, some static webpages and a subscribe button

**Comment by crabdul** [comment]
static site app - for home and about
hackfeed app- the dynamic feed
events app
subscribe newsletter app

**Comment by crabdul** [comment]
I changed the name of the blog app to hackfeed so you had to run ` python manage.py migrate --run-syncdb` to get it working

**Comment by Bishwin** [comment]
general rule of thumb is that if any of these apps are independent of each other and won't share models then its fine to separate them.

An exception might be an user authentication app for login/signup
