### ISSUE TITLE
tags on Linkposts overflow

### ISSUE THREAD

**Issue by Bishwin** [hacking-science/hacking-science-website#50]
![image](https://user-images.githubusercontent.com/9053841/36345451-7eea1462-1422-11e8-925f-35983dc0f606.png)

**Comment by crabdul** [comment]
If you remove the display: flex styling from the div with class mdc-card__actions and
add 
`
    overflow: auto;
    white-space: nowrap;
`
to the div with class mdc-card__actions you can scroll through the tags and its contained within the box

**Comment by crabdul** [comment]
![feb-18-2018 12-44-31](https://user-images.githubusercontent.com/23074754/36351994-90e38eaa-14a9-11e8-8fc2-6ec8f5f1c5e6.gif)

**Comment by crabdul** [comment]
The tags are lyrics from a Pixies song…

**Comment by Bishwin** [comment]
looks good. how is the scrolling in mobile?
I agree there should probably be a tag limit per post, maybe no more than 5?

**Comment by crabdul** [comment]
I haven't tried.
Yeah thats a good number. the font-size should probably be smaller as well
