### ISSUE TITLE
Post as an abstract class with subclass for different content types

### ISSUE THREAD

**Issue by crabdul** [hacking-science/hacking-science-website#55]
The post class fields are 

- title
- post type
- description
- tags

which I feel isn't entirely practical for the different content types.
At the moment, the website URL goes in the description field and the author field that will be added for the feature post type will be redundant for the youtube and link post types

Should Post be an abstract class with subclasses 'feature', 'link', and 'youtube'?

I've roughly outlined below what I reckon they could look like.

What are your thoughts?

```
class Post(AbstractBaseClass):
   title
   tags
  summary (short description of what the post is)

class Feature(Post):
   author
   wysiwyg (content)
   image
   slug

class Link(Post):
   url
   image

class Youtube(Post):
   url
  # image will be provided by youtube thumbnail

```

**Comment by harjeetkalsi** [comment]
this looks good, have you had a go at implementing this? would we then also need to change the admin portal to display different fields based upon what type of post is chosen? I actually havent created abstract classes in a while, lol need to refresh my knowledge @Bishwin thoughts?

**Comment by Bishwin** [comment]
I like this idea, though i think author should also be in the base class. 

What are your thoughts on posts containing multiples of these types?
Someone may want to make a post with embedded `youtube` and website `links`, would this be a `feature post` with these links added as content?
Weird analogy but I imagine a Post like a pizza, it can have multiple different toppings/post types within it. should we offer contributors to a way to customise their post or have a set of predefined post types like these?

now i'm just thinking out loud, do we want multiple post types or have posts contain different content types?

**Comment by crabdul** [comment]
@Bishwin Yes agreed with author in the base class

Exactly, that'd be a feature post.  Because the feature post will have a WYSIWYG editor, they can include youtube videos as iframes and links formatted in markdown.

haha great pizza analogy.
I think predefined post types are preferred as the model fields for them vary a fair bit.

In order to query the different post types when rendering the feed, I think this [plugin](https://django-model-utils.readthedocs.io/en/latest/managers.html) is required. It's written by someone on the django team so it's probably trustworthy. 

Or any other ideas on how to implement this?

**Comment by crabdul** [comment]
@harjeetkalsi I'll have a go!

**Comment by crabdul** [comment]
completed in #70
