### ISSUE TITLE
Adding a footer 

### ISSUE THREAD

**Issue by harjeetkalsi** [hacking-science/hacking-science-website#57]
The front end is starting to look great, a footer is however needed which should contain the hackingEducation logo, contact details (info@hackingeducation.io), facebook page (placeholder for now until we have one), any thing else you think?

**Comment by crabdul** [comment]
copyright and I think that's pretty much it

**Comment by harjeetkalsi** [comment]
sweet!

**Comment by crabdul** [comment]
#69
