### ISSUE TITLE
Adding a hackingeducation news style post that will appear on the homepage

### ISSUE THREAD

**Issue by harjeetkalsi** [hacking-science/hacking-science-website#60]
### What would you like to change?
On the homepage after the 'our work' titles, it would be good to have a 'latest in hacking news' . 
This would require all posts with hackingeducation news to require a certain style, and have the tag 'hEnews' automatically assigned to it. 

### How do you think that would improve the project?
Would improve the homepage and help people to stay updated.

**Comment by crabdul** [comment]
Do you reckon this should solely be a widget or should you be able to click on specific news articles and be taken to a page where you can read the article in full at a url like `news/march-review`?

I guess it depends on how long these news articles will be.

Or maybe we just create a twitter account and use their widget?

One bonus I think we'll have with the twitter widget is to supply news to the website and followers concurrently, and I reckon that just by the fact that it's easy to use it'll be used much more frequently.

But what if there is big news that can't be summarised in 240 characters?

Then we should probably have a news section. I like [Shine's newssection](https://www.shinetrust.org.uk/news/)

Sorry for blabbing
